DROP TABLE IF EXISTS universidades;

CREATE TABLE universidades(
    Año INT,
    Cod_Inst INT PRIMARY KEY,
<<<<<<< HEAD
    Nombre_Institución VARCHAR (70),
=======
    Nombre_Institución INT,
>>>>>>> cbdf8cd8a0678c9ec752b4bbc3c4ee7ec584c388
    Tipo_Institución VARCHAR (10),
    Clasificación1 VARCHAR (50),
    Clasificación2 VARCHAR (50),
    Clasificación3 VARCHAR (50),
    Clasificación4 VARCHAR (50),
    Clasificación5 VARCHAR (50),
    Nombre_sede VARCHAR (50),
    Comuna_sede VARCHAR (50),
    Nombre_Región VARCHAR (25),
    Orden_Geográfico VARCHAR (10),
    Cód_Carrera INT UNIQUE,
    Carrera_genérica VARCHAR (120),
    Nombre_programa VARCHAR (120),
    Mención_Especialidad VARCHAR (120),
    Horario VARCHAR (10),
    Tipo_programa VARCHAR (25),
    Area_conocimiento VARCHAR (25),
    idgenerocarrera VARCHAR (10),
    Tipo_carrera VARCHAR (20),
    IngresoDirecto INTEGER,
    Año_inicio VARCHAR(4),
    NombreCampus VARCHAR (40),
    Duración_semestres VARCHAR (2),
    Cód_campus VARCHAR (10),
    Cód_sede VARCHAR (10),
    Título VARCHAR (40),
    Grado_académico VARCHAR (40),
    Máximo_puntaje_psu_prom_math_leng VARCHAR (3),
    Promedio_pje_psu_prom_math_leng VARCHAR (3),
    Mínimo_puntaje_psu_prom_math_leng VARCHAR (3),
    Puntaje_corte_primerselec VARCHAR (3),
    Puntaje_corte_promcarrera VARCHAR (3),
    Puntaje_corte_ultselec VARCHAR (3),
    Máximo_pje_nem VARCHAR (3),
    Promedio_pje_nem VARCHAR (3),
    Mínimo_pje_nem VARCHAR (3),
    Máximo_pje_ranking VARCHAR (3),
    Promedio_pje_ranking VARCHAR (3),
    Mínimo_pje_ranking VARCHAR (3),
    Número_alumnos_ingreso_psu VARCHAR (5),
    Número_alumnos_otro_ingreso VARCHAR (5),
    Valor_matricula VARCHAR (9),
    Valor_arancel VARCHAR (9),
    Valor_título VARCHAR (9),
    Vacantes VARCHAR (5),
    Matrícula_primer_año_hombres VARCHAR (5),
    Matrícula_primer_año_mujeres VARCHAR (5),
    Matrícula_primer_año_extranjero VARCHAR (5),
    Matrícula_primer_año VARCHAR (5),
    Matrícula_total_hombres VARCHAR (5),
    Matrícula_total_mujeres VARCHAR (5),
    Matrícula_total_extranjero VARCHAR (5),
    Matrícula_total VARCHAR (6),
    Matrícula_total_cohorte_año_anterior VARCHAR (2),
<<<<<<< HEAD
    Cód_sies INT,
=======
    Cód_sies VARCHAR (14),
>>>>>>> cbdf8cd8a0678c9ec752b4bbc3c4ee7ec584c388
    Pregado_postgrado VARCHAR (10)
);