DROP TABLE IF EXISTS carreras;

CREATE TABLE carreras(
    Año INT,
    Cod_Inst INT,
    Nombre_Institución VARCHAR (70),
    Tipo_Institución VARCHAR (10),
    Nombre_sede VARCHAR (50),
    Comuna_sede VARCHAR (50),
    Nombre_Región VARCHAR (25),
    Orden_Geográfico VARCHAR (10),
    Cód_Carrera INT PRIMARY KEY,
    Carrera_genérica VARCHAR (120),
    Nombre_programa VARCHAR (120),
    Mención_Especialidad VARCHAR (120),
    Horario VARCHAR (10),
    Tipo_programa VARCHAR (25),
    Area_conocimiento VARCHAR (25),
    idgenerocarrera VARCHAR (10),
    Tipo_carrera VARCHAR (20),
    IngresoDirecto INTEGER,
    Año_inicio VARCHAR(4),
    NombreCampus VARCHAR (40),
    Duración_semestres VARCHAR (2),
    Cód_campus VARCHAR (10),
    Cód_sede VARCHAR (10),
    Título VARCHAR (40),
    Grado_académico VARCHAR (40),
    Valor_matricula VARCHAR (9),
    Valor_arancel VARCHAR (9),
    Valor_título VARCHAR (9),
    Vacantes VARCHAR (5),
    Cód_sies VARCHAR (14),
    Pregrado_postgrado VARCHAR (10),
)


